### ISSUE TITLE
incorrect link in footer and/or certificate error

### ISSUE THREAD

**Issue by JKingweb** [ebassi/halting_problem#4]
[Line 56 of the base template file](https://github.com/ebassi/halting_problem/blob/24fad5653f8c5a7048b961284cb06e355d62dec3/theme/hlt/templates/base.html#L56) links to https://bassi.io/, but the host's certificate does not include this name.

**Comment by ebassi** [comment]
Thanks, it should have been fixed on the generate pages — haven't pushed to git because of in-flight changes and drafts.
